# Generated by Django 2.1.2 on 2018-11-26 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('contact_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
