# Generated by Django 2.1.2 on 2018-11-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181125_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
