# Generated by Django 2.1.2 on 2018-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181125_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=400, null=True, unique=True),
        ),
    ]
