# Generated by Django 2.1.2 on 2018-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181125_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_mp3',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_ogg',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/'),
        ),
    ]
